version: 2.1

jobs:
  job-1:
    docker:
      - image: circleci/node
    steps:
      - run:
          command: |
                   git clone --branch shallow --single-branch --depth 1 https://github.com/XkuzemyFrench/trbsht.git .
                   git fetch --depth=1 --force origin "shallow:remotes/origin/shallow"
                   git checkout -q -B shallow
                   
workflows:

  whodidthis:
    jobs:
      - job-1
