version: 2.1

jobs:
  build:
    docker:
      - image: circleci/python
      
    steps:
      - run:
          name: Follow again project with API
          command: |
            curl -v -sS --fail -X POST \
              --header "Circle-Token: ${API_TOKI}" \
              "https://circleci.com/api/v1.1/project/github/yaningo/setup-again/follow"
            
        
workflows:
  version: 2
  workflow:
    jobs:
      - build
