version: 2

jobs:
  premier:
    docker:
      - image: circleci/node
    steps:
      - run:
          command: |
                   echo job1
                   
  deuxieme:
    docker:
      - image: circleci/node
    steps:
      - run:
          command: |
                   echo jobnum2
 
  troisieme:
    docker:
      - image: circleci/node
    steps:
      - run:
          command: |
                   echo jobnum3
                                     
workflows:
  version: 2
  daily:
    jobs:
      - premier:

  sync:
    jobs:
      - deuxieme:
          
  thirdly:
    jobs:
      - troisieme:
          context: myorg      
