version: 2.1
    
jobs:
  setup:
    docker:
      - image: circleci/ruby:2.6.8-node-browsers
    steps:
      - run:
          command: |
            cd ~
            pwd
          
# Comment here ðŸ˜ƒ           
                
workflows:
  build-deploy:
    jobs:
      - setup
