version: 2.1
    
jobs:
  setup:
    machine:
      image: ubuntu-2004:202111-01
    steps:
      - run: |
          aws --version
# Comment here ðŸ˜ƒ           
                
workflows:
  build-deploy:
    jobs:
      - setup
