version: 2.1

orbs:
  detect: circleci/os-detect@0.3.0
  
parameters:
      lacondition:
        description: La condition
        type: string
        default: $condition_needed
        
commands: # a reusable command with parametersssssss
  greeting:
    parameters:
      to:
        default: "world"
        type: string
    steps:
      - run:
          name: Greetings
          command: echo "Hello << parameters.to >>"
      
jobs:
  messer:
    docker:
      - image: circleci/node
    steps:
      - detect/init:
          extended: false
          
      - run: |
          echo << pipeline.parameters.lacondition >>
          echo "Oh la laaaaa" 
          echo $condition_needed
          
      - when:
          condition:
            equal: [ "true", << pipeline.parameters.lacondition >> ]
          steps:
            - run:
                name: Testing env_var_name interpolation
                command: |
                  echo "Step by step"
                  echo << pipeline.parameters.lacondition >>
                  echo "Wooohoo Ã‡a marche !!!!!!"
      
      - greeting:
          to: << pipeline.parameters.lacondition >>
          

# Orchestrate or schedule a set of jobs
workflows:
  # Name the workflow "welcome"
  welcome:
    jobs:
      - messer
